spring.application.name=DOSW-Library
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/library_db
spring.datasource.username=library_user
spring.datasource.password=library_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB
spring.data.mongodb.uri=mongodb+srv://juandavidvaleroa_db_user:Gaby123@cluster0.yjwhg73.mongodb.net/dosw_library?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=dosw_library

# Spring Profiles - Activar profile mongo para usar MongoDB como persistencia
spring.profiles.active=mongo

# JWT
jwt.secret=dosw-library-secret-key-2026-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=3600000
